// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pin.CricketDarts.Infrastructure.Data;

#nullable disable

namespace Pin.CricketDarts.Infrastructure.Migrations
{
    [DbContext(typeof(DbDartsContext))]
    partial class DbDartsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatchPlayer", b =>
                {
                    b.Property<Guid>("MatchesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MatchesId", "PlayersId");

                    b.HasIndex("PlayersId");

                    b.ToTable("MatchPlayer");

                    b.HasData(
                        new
                        {
                            MatchesId = new Guid("6c5f4c20-79c8-4bd1-8d41-02c1d6f3bc5b"),
                            PlayersId = new Guid("1795865f-087b-4f50-afb0-6dca38280b4a")
                        },
                        new
                        {
                            MatchesId = new Guid("6df8e9d8-f81e-4ac9-be1b-e2632766a9e6"),
                            PlayersId = new Guid("1795865f-087b-4f50-afb0-6dca38280b4a")
                        },
                        new
                        {
                            MatchesId = new Guid("6c5f4c20-79c8-4bd1-8d41-02c1d6f3bc5b"),
                            PlayersId = new Guid("df8ae62d-75f0-47e4-b099-0a8d0fc2fac0")
                        },
                        new
                        {
                            MatchesId = new Guid("6df8e9d8-f81e-4ac9-be1b-e2632766a9e6"),
                            PlayersId = new Guid("df8ae62d-75f0-47e4-b099-0a8d0fc2fac0")
                        });
                });

            modelBuilder.Entity("Pin.CricketDarts.Core.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActiveGame")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerOneScore")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTwoScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c5f4c20-79c8-4bd1-8d41-02c1d6f3bc5b"),
                            IsActiveGame = false,
                            PlayerOneScore = 0,
                            PlayerTwoScore = 0,
                            TimeStamp = new DateTime(2022, 11, 25, 13, 52, 19, 317, DateTimeKind.Local).AddTicks(3028)
                        },
                        new
                        {
                            Id = new Guid("6df8e9d8-f81e-4ac9-be1b-e2632766a9e6"),
                            IsActiveGame = false,
                            PlayerOneScore = 0,
                            PlayerTwoScore = 0,
                            TimeStamp = new DateTime(2022, 11, 25, 15, 52, 19, 317, DateTimeKind.Local).AddTicks(3065)
                        });
                });

            modelBuilder.Entity("Pin.CricketDarts.Core.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1795865f-087b-4f50-afb0-6dca38280b4a"),
                            Firstname = "Benny",
                            Lastname = "Van Meerbeeck"
                        },
                        new
                        {
                            Id = new Guid("df8ae62d-75f0-47e4-b099-0a8d0fc2fac0"),
                            Firstname = "Arlette",
                            Lastname = "Verheugen"
                        });
                });

            modelBuilder.Entity("Pin.CricketDarts.Core.Entities.PlayerThrow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ScoreId");

                    b.ToTable("PlayerThrows");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd113963-edaf-458a-9c60-c0a0e3441778"),
                            MatchId = new Guid("6df8e9d8-f81e-4ac9-be1b-e2632766a9e6"),
                            PlayerId = new Guid("1795865f-087b-4f50-afb0-6dca38280b4a"),
                            ScoreId = new Guid("96380c15-7f0e-4a3e-850e-a60abde44c26"),
                            TimeStamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9fc52830-5b1f-4bf5-a732-7339cdb51a30"),
                            MatchId = new Guid("6c5f4c20-79c8-4bd1-8d41-02c1d6f3bc5b"),
                            PlayerId = new Guid("1795865f-087b-4f50-afb0-6dca38280b4a"),
                            ScoreId = new Guid("272d5916-d333-42bc-8b11-8efba96180ee"),
                            TimeStamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a69efc55-3e83-464a-8451-6cd4d32b1170"),
                            MatchId = new Guid("6c5f4c20-79c8-4bd1-8d41-02c1d6f3bc5b"),
                            PlayerId = new Guid("1795865f-087b-4f50-afb0-6dca38280b4a"),
                            ScoreId = new Guid("ff5d7ab5-76cc-4212-9f45-8d0de4dfdbb1"),
                            TimeStamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fffc6ac8-9014-4d6a-8762-b1d3557406e1"),
                            MatchId = new Guid("6c5f4c20-79c8-4bd1-8d41-02c1d6f3bc5b"),
                            PlayerId = new Guid("1795865f-087b-4f50-afb0-6dca38280b4a"),
                            ScoreId = new Guid("07270342-f74c-493f-8fa5-12847246a68d"),
                            TimeStamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ce639335-402d-4b37-8e72-f06ab500d6f7"),
                            MatchId = new Guid("6df8e9d8-f81e-4ac9-be1b-e2632766a9e6"),
                            PlayerId = new Guid("df8ae62d-75f0-47e4-b099-0a8d0fc2fac0"),
                            ScoreId = new Guid("ff5d7ab5-76cc-4212-9f45-8d0de4dfdbb1"),
                            TimeStamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2a18e5b6-e98b-4cf9-956f-9bbb54a55a81"),
                            MatchId = new Guid("6c5f4c20-79c8-4bd1-8d41-02c1d6f3bc5b"),
                            PlayerId = new Guid("df8ae62d-75f0-47e4-b099-0a8d0fc2fac0"),
                            ScoreId = new Guid("3913367c-9305-4bc7-b3df-f88606a45ed7"),
                            TimeStamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6ba23dd6-339c-47fe-87f2-be44f7293058"),
                            MatchId = new Guid("6c5f4c20-79c8-4bd1-8d41-02c1d6f3bc5b"),
                            PlayerId = new Guid("df8ae62d-75f0-47e4-b099-0a8d0fc2fac0"),
                            ScoreId = new Guid("8862cbd5-f93f-4efd-b58a-36e871c7b9bf"),
                            TimeStamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2373743d-6597-4859-8054-78590047e61f"),
                            MatchId = new Guid("6c5f4c20-79c8-4bd1-8d41-02c1d6f3bc5b"),
                            PlayerId = new Guid("df8ae62d-75f0-47e4-b099-0a8d0fc2fac0"),
                            ScoreId = new Guid("b2e00493-4f3b-4b05-931e-d15514fbe6f0"),
                            TimeStamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Pin.CricketDarts.Core.Entities.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OriginalScore")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Score")
                        .IsUnique();

                    b.ToTable("Throws");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96380c15-7f0e-4a3e-850e-a60abde44c26"),
                            OriginalScore = 15,
                            Score = 15
                        },
                        new
                        {
                            Id = new Guid("272d5916-d333-42bc-8b11-8efba96180ee"),
                            OriginalScore = 15,
                            Score = 30
                        },
                        new
                        {
                            Id = new Guid("ee09d5e1-945a-4e08-87c7-142f5db84258"),
                            OriginalScore = 15,
                            Score = 45
                        },
                        new
                        {
                            Id = new Guid("819e0c39-d956-4d1b-a584-5af18a92dcf7"),
                            OriginalScore = 16,
                            Score = 16
                        },
                        new
                        {
                            Id = new Guid("ff5d7ab5-76cc-4212-9f45-8d0de4dfdbb1"),
                            OriginalScore = 16,
                            Score = 32
                        },
                        new
                        {
                            Id = new Guid("ef529ab2-314f-42b6-8fdd-1a64280b972d"),
                            OriginalScore = 16,
                            Score = 48
                        },
                        new
                        {
                            Id = new Guid("07270342-f74c-493f-8fa5-12847246a68d"),
                            OriginalScore = 17,
                            Score = 17
                        },
                        new
                        {
                            Id = new Guid("76407199-05cb-4caf-a2d2-4b8c0c8a2938"),
                            OriginalScore = 17,
                            Score = 34
                        },
                        new
                        {
                            Id = new Guid("3913367c-9305-4bc7-b3df-f88606a45ed7"),
                            OriginalScore = 17,
                            Score = 51
                        },
                        new
                        {
                            Id = new Guid("4193d23b-6bee-415f-b44e-c67d42dd546d"),
                            OriginalScore = 18,
                            Score = 18
                        },
                        new
                        {
                            Id = new Guid("7dbb9e71-f682-41ce-bbe0-816918667b40"),
                            OriginalScore = 18,
                            Score = 36
                        },
                        new
                        {
                            Id = new Guid("fad69be9-f029-4adc-bf6c-072eb6e77a1a"),
                            OriginalScore = 18,
                            Score = 54
                        },
                        new
                        {
                            Id = new Guid("3842191c-37e8-44b6-b68f-bf4d36f3a495"),
                            OriginalScore = 19,
                            Score = 19
                        },
                        new
                        {
                            Id = new Guid("57789352-df96-4c5d-9954-1ba279f8672c"),
                            OriginalScore = 19,
                            Score = 38
                        },
                        new
                        {
                            Id = new Guid("4cb5cd0c-1a80-475c-8af0-8236ca30382a"),
                            OriginalScore = 19,
                            Score = 57
                        },
                        new
                        {
                            Id = new Guid("3406eb3a-451d-45b4-b307-66112a9dcddc"),
                            OriginalScore = 20,
                            Score = 20
                        },
                        new
                        {
                            Id = new Guid("8862cbd5-f93f-4efd-b58a-36e871c7b9bf"),
                            OriginalScore = 20,
                            Score = 40
                        },
                        new
                        {
                            Id = new Guid("f812a8a8-6f57-4357-a049-5b88e42b38f3"),
                            OriginalScore = 20,
                            Score = 60
                        },
                        new
                        {
                            Id = new Guid("961b6d53-83c1-4f51-9264-448e92190192"),
                            OriginalScore = 25,
                            Score = 25
                        },
                        new
                        {
                            Id = new Guid("b2e00493-4f3b-4b05-931e-d15514fbe6f0"),
                            OriginalScore = 25,
                            Score = 50
                        });
                });

            modelBuilder.Entity("MatchPlayer", b =>
                {
                    b.HasOne("Pin.CricketDarts.Core.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pin.CricketDarts.Core.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pin.CricketDarts.Core.Entities.PlayerThrow", b =>
                {
                    b.HasOne("Pin.CricketDarts.Core.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pin.CricketDarts.Core.Entities.Player", "Player")
                        .WithMany("AllThrows")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pin.CricketDarts.Core.Entities.Point", "Score")
                        .WithMany("PlayerThrows")
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("Pin.CricketDarts.Core.Entities.Player", b =>
                {
                    b.Navigation("AllThrows");
                });

            modelBuilder.Entity("Pin.CricketDarts.Core.Entities.Point", b =>
                {
                    b.Navigation("PlayerThrows");
                });
#pragma warning restore 612, 618
        }
    }
}
